export const READ_BRANCHES_SUCCESSFUL = 'READ_BRANCHES_SUCCESSFUL';
export const READ_BRANCHES_PENDING = 'READ_BRANCHES_PENDING';
export const READ_BRANCHES_FAILURE = 'READ_BRANCHES_FAILURE';

export const READ_COPIES_SUCCESSFUL = 'READ_COPIES_SUCCESSFUL';
export const READ_COPIES_PENDING = 'READ_COPIES_PENDING';
export const READ_COPIES_FAILURE = 'READ_COPIES_FAILURE';

export const CHECKOUT_BOOK_SUCCESSFUL = 'CHECKOUT_BOOK_SUCCESSFUL';
export const CHECKOUT_BOOK_PENDING = 'CHECKOUT_BOOK_PENDING';
export const CHECKOUT_BOOK_FAILURE = 'CHECKOUT_BOOK_FAILURE';

export const CHANGE_BRANCH = 'CHANGE_BRANCH';


