//Login Actions
export const LOGIN_ATTEMPT_PENDING = 'LOGIN_ATTEMPT_PENDING';
export const LOGIN_ATTEMPT_SUCCESSFUL = 'LOGIN_ATTEMPT_SUCCESSFUL';
export const LOGIN_ATTEMPT_FAILURE = 'LOGIN_ATTEMPT_FAILURE';
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';