export const READ_LOANS_SUCCESSFUL = 'READ_LOANS_SUCCESSFUL';
export const READ_LOANS_PENDING = 'READ_LOANS_PENDING';
export const READ_LOANS_FAILURE = 'READ_LOANS_FAILURE';

export const RETURN_BOOK_SUCCESSFUL = 'RETURN_BOOK_SUCCESSFUL';
export const RETURN_BOOK_PENDING = 'RETURN_BOOK_PENDING';
export const RETURN_BOOK_FAILURE = 'RETURN_BOOK_FAILURE';

export const CHANGE_PAGE = 'CHANGE_PAGE';